# Generated by Django 4.0.2 on 2022-04-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_scalpingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalpingorder',
            name='currentdate',
            field=models.CharField(default='0000000', max_length=200),
        ),
    ]
