# Generated by Django 4.0.2 on 2022-04-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_scalpingorder_currentdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='logged_in_client',
            new_name='accessCode',
        ),
    ]
