# Generated by Django 4.0.2 on 2022-04-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_rename_logged_in_client_user_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalpingorder',
            name='userid',
            field=models.CharField(default='00000000000', max_length=200),
        ),
    ]
