# Generated by Django 4.0.2 on 2022-04-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_scalpingorder_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scalpingOrderid', models.CharField(max_length=200)),
                ('instrument_token', models.CharField(max_length=200)),
                ('equivalentOrderPrice', models.CharField(max_length=200)),
                ('order_type', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=200)),
                ('order_status', models.CharField(max_length=200)),
                ('initialOrderType', models.CharField(max_length=200)),
                ('startPrice', models.CharField(max_length=200)),
            ],
        ),
    ]
