# Generated by Django 4.0.2 on 2022-04-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalpingorder',
            name='status',
            field=models.CharField(default='active', max_length=200),
        ),
    ]
