# Generated by Django 4.0.2 on 2022-04-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_scalpingorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='instrumenttype',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='scalpingorder',
            name='instrumenttype',
            field=models.CharField(default='', max_length=200),
        ),
    ]
