# Generated by Django 4.0.2 on 2022-04-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_orderhistory_instrumenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_id',
            field=models.CharField(default='00000000000', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='00000000000', max_length=200),
        ),
        migrations.AlterField(
            model_name='scalpingorder',
            name='status',
            field=models.CharField(default='stop', max_length=200),
        ),
    ]
