# Generated by Django 4.0.2 on 2022-04-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0010_user_app_id_user_password_alter_scalpingorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalpingorder',
            name='currentdate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scalpingorder',
            name='userid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='app_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
