# Generated by Django 4.0.2 on 2022-04-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0011_alter_scalpingorder_currentdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalpingorder',
            name='instrumentTag',
            field=models.CharField(default='', max_length=200),
        ),
    ]
