# Generated by Django 4.0.2 on 2022-04-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0012_scalpingorder_instrumenttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='stop', max_length=200)),
            ],
        ),
    ]
