# Generated by Django 4.0.2 on 2022-04-17 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0014_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='userid',
        ),
    ]
