# Generated by Django 4.0.2 on 2022-04-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0015_remove_favourite_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='instrumentTag',
            field=models.CharField(default='', max_length=200),
        ),
    ]
