# Generated by Django 4.0.2 on 2022-05-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0016_favourite_instrumenttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='RememberMeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('consumer_key', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=200)),
                ('accessCode', models.TextField()),
                ('app_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
